### ISSUE TITLE
Request to add license/permission to fork & publish

### ISSUE THREAD

**Issue by nelsontm** [violetbp/lc2k#5]
Hello! I am on staff with EECS 370 and really loved this extension when I was a student. I was wondering if the EECS 370 Staff (@eecs370) can fork this repo to update/maintain it as we make small changes to LC2K. If that sounds good to you, would you be willing to add a small license to the repo permitting copy and modification?

**Comment by vivianbp** [comment]
absolutely! glad you enjoyed it enough to want to continue development :D
it looks like mit is the best choice so I've added that just now, so you should be all set
Probably makes the most sense to create a new extension so yall have ownership, if you want to submit a PR to this repo pointing the readme and name to the new repo and extension I can merge it to make sure people don't get confused.
